### ISSUE TITLE
Issue for [API implementation for artists/ endpoint] milestone

### ISSUE THREAD

**Issue by paulsoh** [paulsoh/art_archive#5]
1. Implementation
2. Make unittest code

**Comment by paulsoh** [comment]
artists/ endpoint, `GET` 메소드에 대한 기능을 구현하였습니다.
68a98262b52a7c1a1f66ca5ba1050bcae89d2b6a

DRY가 아닌 RY적인 요소가 다소 있는데, 이 부분은 추후 리팩토링하도록 하겠습니다.

**Comment by paulsoh** [comment]
현재 15:00 진행 상황 
- artists/ endpoint, `POST` 메소드에 대한 기능을 구현하였습니다. 93bee3bd6fb09aae346eb059b593f67015983280
- 간단하게 `POST`를 테스트할 수 있는 `client.html`을 만들었습니다. 0c152de7dd97b67fd76e481c34ff6a3c948d9ed4

고민 사항
- json response를 주는 과정에서 jsonify를 너무 남용하고 있습니다. 이 부분은 이번 `artists`  endpoint 구현에 대한 PR를 하기전에 리팩토링을 하도록 하겠습니다.
- `artists/` unit test를 추가하고, artists/:id, artists/:id/artworks, artists/search 에 대한 부분을 구현하도록 하겠습니다.

**Comment by yeaz** [comment]
@paulsoh Unit Test 는 사실 Project 3 에서 진행할 예정이기 때문에 이번에 test 까지 추가하실 필요가 없을 것 같습니다.

**Comment by yeaz** [comment]
@paulsoh jsonify 를 남용하는 것이 어떤 문제가 있을까요? 그리고 refactoring 을 할 때 어떤 부분을 해소하려는 것이 목적인가요?

**Comment by paulsoh** [comment]
헉 댓글을 늦게 봤네요.. 일단은 `artists/` endpoint 에 대한 unittest를 방금 커밋하였습니다. 79a6ba1553e3d238f2d6b08fdd13a9872c98b81f

**Comment by paulsoh** [comment]
@yeaz `jsonify`를 남용한 것을 리팩토링 하겠다고 한 제 표현이 조금 부족했던 것 같습니다. 제가 코드를 하면서 리팩토링이 필요하겠다고 생각한 부분은 다음과 같은 부분입니다.

```
return jsonify(
    {
        "meta": {
            "response_code": 422,
            "error_type": "UNPROCESSABLE ENTRY",
            "error_msg": "count parameter must be 'positive' integer",
        },
        "data": None
    }
)
```

제가 설계한 바에 따르면, API에서 모든 json response는 `meta`와 `data`를 갖게 되는데 이 부분이 너무 반복적으로 나타나고 있습니다. 그래서 이 부분을 리팩토링을 할 예정이라는 것을 말씀드렸습니다.

리팩토링 방법은 고민중인데 아마 custom decorator를 만들어서 사용하는 방법을 이용할 것 같습니다.

**Comment by yeaz** [comment]
@paulsoh 좋은 고민인 것 같습니다. 이 부분을 Project 1 할 때 피드백 드리려다가 일단은 지나쳤던 부분이기도 한데요,

지금 meta 에 들어가는 정보는 사실 HTTP Response 의 header 내용과 일치합니다. 또한 422 라고 Response Code 를 설정한다면 자연스럽게 그건 error_type 이 "UNPROCESSABLE ENTITY" 가 되기 때문에 별도로 위와 같이 코드에 쓸 필요가 없어지겠죠. 그렇다면 meta 단계에서 유일하게 custom 한 부분은 error_msg 인데 이를 밑에 None 인 data 로 옮길 수 있습니다. 정리하자면,

```
 {
        "meta": {
            "response_code": 422,
            "error_type": "UNPROCESSABLE ENTRY",
            "error_msg": "count parameter must be 'positive' integer",
        },
        "data": None
   }
```

becomes

```
HTTP CODE: 422 Unprocessable Entity
{
  "error": "count parameter must be 'positive integer"
}
```

HTTP Response Code 를 어떻게 설정하는지를 별도로 찾아보시면 이렇게 구현하실 수 있을 것입니다.
만약에 이렇게 구현을 바꾸시려면, 해당 API Documentation도 수정해주시면 좋을 것 같습니다.

**Comment by paulsoh** [comment]
@yeaz 말씀하신대로 헤더부와 중복되는 내용은 뺴는 게 좋을 것 같습니다. API Documentation에 반영하도록 하겠습니다.

**Comment by paulsoh** [comment]
@yeaz API documentation 변경 내용 반영 완료하였습니다. e6ca458112b2ef630c5628a6516400a3908e3e4b

**Comment by paulsoh** [comment]
#5, #6 이슈 완료하였습니다.

**Comment by paulsoh** [comment]
#7 이슈: `artists/artist_id/artworks` endpoint 구현 완료. 5547486743c52b957b675a4ad3c3b8fc4927e70e

**Comment by paulsoh** [comment]
#8 이슈: `artists/search/` endpoint 구현 완료. b381f928fe77fecb79e9c5c5f0b67f6da17124be

**Comment by paulsoh** [comment]
현재 21:00 진행 상황
- `artists/` endpoint 구현 완료(이슈 #5, #6, #7, #8)
- API documentation 현실화 완료
- `artists/`과 관련한 기능 구현을 `feature/artists_lists_endpoint` 브랜치 상에 하였습니다.
- `develop` 브랜치로 merge를 위한 PR를 보내드리겠습니다.

**Comment by paulsoh** [comment]
`artists/` endpoint 구현 완료에 대한 PR입니다. https://github.com/paulsoh/art_archive/pull/17
